# Generated by Django 4.1.5 on 2023-03-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="postModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("desc", models.CharField(max_length=200)),
                (
                    "cond",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("like-new", "like-new"),
                            ("used-good", "used-good"),
                            ("used", "used"),
                        ],
                        max_length=100,
                    ),
                ),
                ("price", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
