# Generated by Django 4.1.5 on 2023-03-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_postmodel_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="buyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "browse_by",
                    models.CharField(
                        choices=[
                            ("name", "name"),
                            ("condition", "condition"),
                            ("price", "price"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
