# Generated by Django 4.1.5 on 2023-03-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_buymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buymodel",
            name="browse_by",
            field=models.CharField(
                choices=[("name", "name"), ("cond", "condition"), ("price", "price")],
                max_length=100,
            ),
        ),
    ]
