# Generated by Django 4.1.5 on 2023-03-18 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0006_postmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="cond",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("like-new", "like-new"),
                    ("used-good", "used-good"),
                    ("used", "used"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="desc",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
